# Generated by Django 6.0.5 on 2026-05-30 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('price', models.FloatField(verbose_name='Цена аренды')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите фото книги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('reservation_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Забронировать можно минимум на 1 день'), django.core.validators.MaxValueValidator(5, message='Забронировать можно максимум на 5 дней')], verbose_name='Количество дней бронирования')),
                ('user_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к бронированию (не обязательно)')),
            ],
        ),
    ]
