# Generated by Django 6.0.5 on 2026-05-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrtour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourcategory',
            old_name='category',
            new_name='name',
        ),
    ]
