# Generated by Django 6.0.5 on 2026-06-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrtour', '0002_rename_category_tourcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsetour',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
